### ISSUE TITLE
flatpak-builder throws errors

### ISSUE THREAD

**Issue by btreut** [cho2/com.rstudio.RStudio#1]
when I tried to follow the instructions, flatpak builder threw an "error:  org.kde.Sdk 5.10 not installed", which could be resolved by installing that version, but then it threw another one:
"Failed to download sources: module ant: Wrong sha256 for apache-ant-1.10.2-bin.zip, expected a8e6320476b721215988819bc554d61f5ec8a80338485b78afbe51df0dfcbc4d, was 5d0214f22dbdaa5beaa82a15e1b2e3f5a377a3985bf2aee350654fa4e37b78b6" 
Is it correct to change the hash in com.rstudio.RStudio.json to the new value or what should I do?
When I correct the sha256 value in com.rstudio.RStudio.json, the next error pops up during the build of module boost:
"Error: module boost: Invalid buildsystem: "simple""
Now I am finally lost, any help is appreciated.

**Comment by cho2** [comment]
I don't know my repo is stiil relevant or not because there are some commits on https://github.com/Alexander-Wilms/flathub/commits/rstudio and my repo is not updated anymore.

Please try https://github.com/Alexander-Wilms/flathub/tree/rstudio and ask the author if you have problem.
